### ISSUE TITLE
Collector는 띄웠는데.. 스케줄 서비스 작동 확인까지는 안했다

### ISSUE THREAD

**Issue by yyeennyy** [yyeennyy/VisualRadio#103]
지원이에게

도커 Collector는 띄우고 정상 실행 확인했어요
아 그런데 지금 스케줄 서비스가 정상 동작하는지는 확인을 못했어
그 run()에서 logger 넣었는데 왜인지 로그 확인을 못하네.. 

그래서 수집기 동작 확인 하기 전에
run()에 진입 잘 하는지 확인가능하도록 만들어두면 좋을 것 같아
그게중요할거같아!

그리고 수정전에는 Client.java를 단독으로 실행하려고 했다면
지금은 Gradle 사용해서 dependency 설정 가능하거든? 
그래서 org.json.JSONObject를 import해둔 상태야!! <= 그래서 지금은 이걸로 json 편하게 다룰 수 있어

궁금한 거나 상의할거는 언제든지 물어봐!!! 나 하나두 안바쁨요 부담노노!!

**Comment by jinjiwon** [comment]
오암 참고하겠습니다 :3
