### ISSUE TITLE
비활성 브랜치 삭제

### ISSUE THREAD

**Issue by yyeennyy** [yyeennyy/VisualRadio#132]
# Motivation
브랜치는 현재 작업 진행중인 것만을 남겨두면 깔끔할 것 같습니다.

# How to
그래서 혹시 작업중이지 않은 브랜치는 삭제하는 것이 어떨까요?

**Comment by shxnzxxn** [comment]
확인했습니다!! 지원이까지 브랜치 수정사항 원격에 올려놓은거 확인됐으면 바로 진행하시죠!

**Comment by jinjiwon** [comment]
확인했습니다. 제 브런치 원격에 반영되어 있어서 삭제해도 될 거 같습니다 !
