### ISSUE TITLE
gpu settings

### ISSUE THREAD

**Issue by yyeennyy** [yyeennyy/VisualRadio#141]
# Motivation
gpu settings

# How to
연구실 서버에서는 gpu를 사용가능합니다.
앞으로도 gpu를 사용할 것을 대비하여, gpu와 cpu 모드를 스위칭가능하도록 할 것입니다.
스위칭은 차치하고, 일단 gpu세팅을 주석으로 남겨두겠습니다.

**Comment by yyeennyy** [comment]
이상없는지 최종확인 테스트를 앞두었는데
업로드가 오래걸리는 관계로 (야아아아악간 지치네요!)

일단 취침하고 오전 10시 이내에 pr하겠습니다.

**Comment by shxnzxxn** [comment]
에고.... 도와줄 수 있는게 있다면 언제든지 부탁해주세요

**Comment by yyeennyy** [comment]
gpu 점유 프로세스를 모두 정리하는 코드를 넣었습니다.
(의도치않은 gpu 프로세스가 종료되지 않는지 검토하고 사용해야 합니다. 현 gpu를 사용하는 프로세스를 전부 내립니다.)
cpu 환경에서는 CudaAPIError가 터지기 때문에, 아무 것도 안하도록 예외처리했습니다.
``` python
from numba import cuda

# gpu 메모리 완전 정리
def clean_gpu():
    try:
        device = cuda.get_current_device()
        device.reset()
    except CudaAPIError:
        # CPU 모드에서는 정리할 것이 없다
        pass
```
